import Head from 'next/head';
import Header from 'components/Header';
import Footer from 'components/Footer';
import ContactForm from 'components/Contact/ContactForm';

export default function Contact() {
  return (
    <>
      <Head>
        <title>PrimeFort</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <ContactForm
        title='Get in Touch'
        description='Reach out to us. We can make something awesome together'
        backgroundImagePath='/images/contact_form_bg.jpg'
      />
      <Footer />
    </>
  );
}
