import Head from 'next/head';
import Header from 'components/Header';
import Footer from 'components/Footer';
import Hero from 'components/Initiatives/Hero';
import Intro from 'components/Initiatives/Intro';
import About from 'components/Initiatives/About';
import { Text } from 'elements/Text';
import Partner from 'components/Initiatives/Partner';
import colleges from 'data/colleges';
import Collage from 'components/Initiatives/Collage';
import Stats from 'components/Initiatives/Stats';
import initiativeStats from 'data/initiativeStats';
import { Button } from 'components/Button';
import CTA from 'components/Initiatives/CTA';
import RightArrow from 'public/images/icons/right_arrow.svg';
import about from 'data/about';

const Initiatives = () => {
  return (
    <>
      <Head>
        <title>Initiatives</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero
        title='Help us move towards a more Secure World'
        imagePath='/images/init1.svg'
      />
      <Intro
        textLeft='In order to raise awareness about cybersecurity, we planned the worlds largest cybersecurity awareness camping, 100+ webinars, and 700+ events in 600+'
        textRight=' universities with more than 150000 students. With our team, we successfully provided seminars and training on more than 100 cybersecurity issues. '
      />
      <Collage
        imagePaths={Array(9).fill(`/images/primepilot/primepilot_5.jpg`)}
      />
      <About
        id='primepilot'
        title={
          <>
            What is{' '}
            <Text type='h2' weight='bold' css={{ color: '$accentb500' }}>
              Primepilot?
            </Text>
          </>
        }
        description='Primepilot is a visionary mission that was started 4 years ago, led by our founder, Sriram. We raise awareness about how to deal with cyber dangers, how to deal with online bullying, how to keep personal information safe at no cost for the benefit of society, and how to maintain our community cyber safe. We intend to target students in order to develop more cybersecurity specialists and raise cyber awareness. We are certain that change must begin with the next generation.

'
        imagePath='/images/primepilot_hashtag.png'
      />
      <Stats stats={initiativeStats} />
      <Partner
        id='digisafenations'
        title='What is DigiSafe Nations?'
        text1='Digisafe Nations is the largest cyber security community in India. DSN works with leading industry professionals to deliver you world-class exposure and expertise under one roof. The objective is to raise awareness among youngsters about the need for having a secure online experience and to provide them with the opportunity to pursue a career in cyber security. Our goal is to bridge the gap between antiquated rules and current infrastructure requirements.\n'
        text2='The event was kickstarted by Sriram in October 2019 when he planned, organized, and hosted one of the largest cybersecurity awareness campaigns in Chennai for free, a historic occurrence for India’a Cybersecurity sector. It subsequently led us to discover that it provided us with a very significant family of youngsters across the nation. On October 1, 2019, the event called DSN Digital Security Summit 19 was hosted at the picturesque campus of the Sri Sai Ram Engineering College, Chennai. Over 2000 individuals from various institutions, universities, and schools across three nations crowded the arena. , Former General Officer, Commanding-In-Chief-Indian Army, was among the 15 notable speakers at the event.'
        collegeData={colleges}
      />
      <CTA
        title='Are you in?'
        text='Take a leadership position on cybersecurity,
and learn more about becoming a signatory.'
        button={
          <Button
            href={about.careers.path}
            border
            text='Join us now'
            color='$accentb500'
            icon={RightArrow}
          />
        }
      />
      <Footer />
    </>
  );
};

export default Initiatives;
