import Head from 'next/head';
import Header from 'components/Header';
import Footer from 'components/Footer';
import PressKit from 'components/Media/PressKit';
import links from 'data/links';

export default function Media() {
  return (
    <>
      <Head>
        <title>Media | PrimeFort</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <PressKit title='Press' downloadPath={links.mediaKitDownload} />
      <Footer />
    </>
  );
}
