import Head from 'next/head';
import Header from 'components/Header';
import Hero from 'components/About/Hero';
import Footer from 'components/Footer';
import Vision from 'components/About/Vision';
import Leadership from 'components/About/Leadership';
import team from 'data/team';
import Story from 'components/About/Story';
import Journey from 'components/About/Journey';
import Media from 'components/About/Media';
import { styled } from 'stitches.config';
import Awards from 'components/About/Awards';
import { Typography } from '@mui/material';

const Container = styled('div');

const AwardFile = [
  {
    title: 'Startup India',
    imageURL:
      'https://res.cloudinary.com/djck1safr/image/upload/v1647623994/PF_-LOGO_sgujaa.png',
  },
  {
    title: 'Entrepreneurs Council of India',
    imageURL:
      'https://res.cloudinary.com/djck1safr/image/upload/v1647608831/Entrepreneurs_council_of_india_neard2.jpg',
  },
  {
    title: 'NCDRC - Corner Stone Award',
    imageURL:
      'https://res.cloudinary.com/djck1safr/image/upload/v1647608832/ncdrc-logo_qofpls.png',
  },
];
export default function About() {
  return (
    <Container css={{ position: 'relative', overflowX: 'hidden' }}>
      <Head>
        <title>PrimeFort</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero
        title='We at PrimeFort are focused on building secure systems'
        subtitle='Get to know a bit about the team and what drives us'
        imagePath='/images/about_cover.jpg'
      />
      <Vision
        id='culture'
        title='Our Culture'
        text='As a corporation, we have high aspirations, based on a high-performance culture. Our culture is defined by a set of five values that have been deliberately selected. They serve as guidance for our daily actions. They govern our connections with one another, with our clients, and with the community at large. '
        imagePath='/images/about_vision.png'
      />
      <Story
        id='our-story'
        title='Our Story'
        text='Primefort began through the remarkable journey. Our story begins a few years back when our founders, partnered together and took the initiative of educating and informing the world about the basic concepts, misinformation, and risks associated with cybersecurity.\n
        The start-up was launched with a mission to help people succeed. Since then, Primefort has only evolved. In a relatively short amount of time, Primefort scaled from nothing to millions, empowering us to accomplish our goal to assist as many people as possible. They have delivered over 1.7 lakh presentations to students in the social engineering and cybersecurity niches, as well as over 150 live webinars and conferences in collaboration with notable celebrities.'
        imagePaths={[1, 2, 3, 4].map((i) => `/images/our_story_${i}.jpg`)}
      />
      <Leadership
        id='leadership'
        title='Meet the Leadership Team'
        team={team}
      />
      {/* AWARDS */}
      <Typography
        variant='h3'
        fontWeight='400'
        textAlign='center'
        marginTop='3em'
      >
        Awards
      </Typography>
      <div
        id='awards'
        style={{
          display: 'flex',
          justifyContent: 'space-evenly',
          alignItems: 'center',
          marginTop: '3em',
          flexWrap: 'wrap',
        }}
      >
        {' '}
        {AwardFile.map((item, i) => {
          return <Awards item={item} key={i} />;
        })}
      </div>
      <Journey
        id='our-journey'
        title='Our Journey so far'
        textLeft='What began as a modern start-up with the goal of educating and empowering people has now'
        textRight=' evolved into a mission-driven organization with the goal of securing peoples IT systems.This is our story and we are proud of it '
      />
      <Media
        title='Media Kit'
        text='Please visit our Media page to download our full Media Kit'
        buttonText='Visit Media Page'
      />
      <Footer />
    </Container>
  );
}
