import Head from 'next/head';
import Header from 'components/Header';
import Hero from 'components/Home/Hero';
import LogoStrip from 'components/Home/LogoStrip';
import About from 'components/Home/About';
import services from 'data/services';
import capabilities from 'data/capabilities';
import Services from 'components/Home/Services';
import Footer from 'components/Footer';
import Testimonials from 'components/Home/Testimonials';
import testimonials from 'data/testimonials';
import CTA from 'components/Sections/CTA';
import FoundersNote from 'components/Home/FoundersNote';

export default function Home() {
  return (
    <>
      <Head>
        <title>PrimeFort</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preload' href='/images/home_hero_bg.png' as='image' />
      </Head>
      <Header />
      <Hero />
      <LogoStrip />
      <About
        title='Why Cybersecurity is necessary?'
        description='In the present-day scenario, there’s a dollar value associated with a data breach/security incident and this pushed cyber security into the board room as senior management is concerned about the security posture of their organisation.'
        services={services}
      />
      <Services
        title='How we partner with your business on security services'
        description='Just imagine a group of Cyber Hitmen (of the good kind) between your organisation and the attackers? That’s Primefort. With a range of proactive and reactive cyber security solutions, CISO’s can sleep tight with Primefort. That’s our Promise. '
        cardData={capabilities}
      />
      <Testimonials
        title='Trusted by the world’s most innovative businesses — big and small'
        description={`Primefort’s growth from its humble beginnings to a million-dollar company epitomizes our devotion to solving some of the world’s most sophisticated security challenges.`}
        testimonials={testimonials}
      />
      {/* <FoundersNote
        title={`Founder's Note`}
        text={`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo, nullam felis, pretium magna. Posuere commodo senectus fermentum.\nDpsum dolor sit amet, consectetur adipiscing elit. Leo, nullam felis, pretium magna. Posuere commodo senectus fermentum. Leo, nullam felis, pretium magna. Posuere commodo senectus fermentum Leo, nullam felis, pretium magna. Posuere commodo senectus fermentum.\nFelis, pretium magna. Posuere commodo senectus fermentum.`}
        imagePath='/images/people/sriram.jpg'
      /> */}
      <CTA
        text='We believe great things can start with a conversation. We would love to hear from you.'
        showButton
        imagePath='/images/new_home.svg'
      />
      <Footer />
    </>
  );
}
