import Head from 'next/head';
import Header from 'components/Header';
import services from 'data/services';
import Hero from 'components/Services/Hero';
import Footer from 'components/Footer';
import Intro from 'components/Services/Intro';
import Features from 'components/Services/Features';
import CTA from 'components/Sections/CTA';
import CustomerStory from 'components/Services/CustomerStory';
import Testimonial from 'components/Services/Testimonial';

const MobileAppPenetrationTesting = () => {
  const data = services.mobileAppPentesting;

  return (
    <>
      <Head>
        <title>{data.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero
        title={data.title}
        description={data.description}
        imagePath={data.imagePath}
      />
      <Intro
        benefits={services.mobileAppPentesting.benefits}
        text={data.intro}
        imagePath='/images/mobile_2.svg'
      />
      <Features
        title='What Do We Offer'
        description='The mobile application security method is tailored to the clients specific requirements. The evaluation technique checks both mobile apps and 3rd-party libraries for security flaws. The mobile app is quantitatively as well as dynamically tested to discover vulnerabilities.'
        features={Object.values(data.features)}
      />
      <CustomerStory
        title={data.customerStory.title}
        text={data.customerStory.text}
        imagePath={data.customerStory.imagePath}
      />
      <Testimonial
        text={data.testimonial.text}
        author={data.testimonial.author}
        designation={data.testimonial.designation}
        imagePath={data.testimonial.imagePath}
      />
      <CTA
        text='We believe great things can start with a conversation. We would love to hear from you.'
        showButton
        imagePath='/images/new_home.svg'
        css={{
          '@bp7': {
            paddingTop: 0,
          },
        }}
      />
      <Footer />
    </>
  );
};

export default MobileAppPenetrationTesting;
